### ISSUE TITLE
First PatchEmbed

### ISSUE THREAD

**Issue by phuocnguyen2008** [NKUhealong/H2Former#1]
Dear authors,

Firstly, thank you for your great work.
I am currently re-produce the results on the Skin dataset using your code.
However, a problem related to the first patch_embed block occurred as shown in the figure.
![image](https://user-images.githubusercontent.com/34409468/235681841-6f91787f-2289-40a1-8d09-c17ecbaaddee.png)

Do you know the reason?
Thank you in advance.

**Comment by NKUhealong** [comment]
Please modify the code in H2Former.py as:
![g](https://user-images.githubusercontent.com/47880931/235686172-fb6ed8dd-7bee-46fc-b533-08251520a432.jpg)

**Comment by phuocnguyen2008** [comment]
Thank you for the quick response. Just a follow-up question regarding the train-val-test split.
I cannot find this information in your paper. Can you clarify this?

**Comment by NKUhealong** [comment]
We follow the official testing and training split.
