### ISSUE TITLE
Model Complexity

### ISSUE THREAD

**Issue by phuocnguyen2008** [NKUhealong/H2Former#2]
Dear authors,

I tried to reproduce the results on the IDRiD dataset and have concerns regarding the computational resources you used for the experiments.
You reported that H2Former only takes 33.56G of FLOPs with an input size of 512x512.
When I ran your code, it took 156.8G of FLOPs. Therefore, my system (2xA6000 GPUs: 96GB) runs out of memory, while you only used an RTX3090 GPU (24GB) for training.
![image](https://github.com/NKUhealong/H2Former/assets/34409468/97fe7f06-6367-4917-b18d-ef5fbae76460)
Can you clarify this problem?
Thank you very much.

**Comment by NKUhealong** [comment]
We use mixed-precision for training, and  you can try to reduce the memory footprint in this  way.  In our system, the  FLOPs is 33G.

**Comment by phuocnguyen2008** [comment]
I've tried your suggestion but the problem remains the same.
Can you please provide the training script that you used to produce the FLOPs of 33G?

Thank you very much.

**Comment by NKUhealong** [comment]
![flops](https://github.com/NKUhealong/H2Former/assets/47880931/a2c952f8-751f-4f80-8791-945c069d237c)
The script that  used to produce the FLOPs.

**Comment by phuocnguyen2008** [comment]
I'm sorry for the confusion. 
What I meant is the training script that used mixed precision for training.

I used the following code (attached figure) but it does not work.
![image](https://github.com/NKUhealong/H2Former/assets/34409468/3f83a154-319d-491f-b1d3-6558352f1b87)

Thank you very much.

**Comment by RongcanChen** [comment]
I also have the same problem, how did you solve it?

**Comment by nguyenpbui** [comment]
@RongcanChen I cannot solve it.
