### ISSUE TITLE
About envrionment？

### ISSUE THREAD

**Issue by HUiTUi** [NKUhealong/H2Former#3]
I want transfer u network to other framework, but i can't find timm

![image](https://github.com/NKUhealong/H2Former/assets/56211117/e9c550c3-5773-4b57-8d2b-0c0753030553)

**Comment by NKUhealong** [comment]
pip install timm     can solve thisproblem.

**Comment by HUiTUi** [comment]
OK thanks， I think u should better write a file like "requirement.txt" for the environment installation.
