### ISSUE TITLE
关于Kvasir-SEG 复现结果

### ISSUE THREAD

**Issue by AKshang** [NKUhealong/H2Former#4]
我想请问关于Kvasir-SEG 数据集您是如何拆分的训练集和测试集，是随机选择800张图片作为训练，随机200作为测试吗？我尝试复现在Kvasir-SEG 上的结果，但是IoU只有82左右，离您文章中提到的86.45还有大概4个点的差距。另外，Dice也只有89左右，也还有4个点左右，想请问问题出在哪里，是数据集的划分或者是数据增强吗？我是完全按照您文章中提到的超参数来设置的

**Comment by AKshang** [comment]
@NKUhealong 您在代码中关于Kvasir-SEG数据集初始设置是png格式的，但是我在官网上找到的这个数据集是jpg格式的

**Comment by AKshang** [comment]
![image](https://github.com/NKUhealong/H2Former/assets/97090370/7fabf2ac-17b4-460d-a28a-d2df51e8ee57关于数据增强部分，我有点困惑，因为并没有增加训练集的数据集而是直接在原图上做例如剪裁，反转等操作？

**Comment by AKshang** [comment]
![image](https://github.com/NKUhealong/H2Former/assets/97090370/690fbfc7-5c71-4b9c-88bb-a004368a948e)

**Comment by phuocnguyen2008** [comment]
Hello, 
What is the number of FLOPs in your experiments? 
Are they similar to those in the papers (~33.56G)?
Thank you.

**Comment by ZM8186** [comment]
你好同学，可以交流一下吗

**Comment by AKshang** [comment]
No, as you mentioned in another question, my experiment is also ~156G

**Comment by ZM8186** [comment]
你好同学，我想问一下你的数据集是怎么划分的，还有txt是怎么导入图片名的

**Comment by AKshang** [comment]
Split as the author mentioned in the article, image names using pre.py

**Comment by ZM8186** [comment]
有拆分的代码吗？

**Comment by Xujingkk** [comment]
你好，请问关于MSCA部分的代码在哪儿呀？麻烦各位指路 谢谢！

**Comment by 06Liz** [comment]
where is ./resnet34.pth?
